# Generated by Django 5.2.1 on 2025-05-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_course',
            field=models.ManyToManyField(blank=True, related_name='student', to='courses.course'),
        ),
    ]
