# Generated by Django 5.2.1 on 2025-06-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_user_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['username'], 'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['username'], 'verbose_name': 'Profile', 'verbose_name_plural': 'Profile'},
        ),
        migrations.RemoveField(
            model_name='account',
            name='pk_account',
        ),
        migrations.AddField(
            model_name='account',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='default@example.com', max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='account',
            table='Account',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='Profile',
        ),
    ]
